### List all hosts

GET http://localhost:3000/hosts
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1NTczNzAzNiwiZXhwIjoxNjU1NzQwNjM2fQ.KdJzAj0kwBZ5phBchd9TITOGOGbd3KB4mniZLaasP3o

### Create host

POST http://localhost:3000/hosts
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1NTczNzAzNiwiZXhwIjoxNjU1NzQwNjM2fQ.KdJzAj0kwBZ5phBchd9TITOGOGbd3KB4mniZLaasP3o

{
  "name": "IFPB",
  "address": "www.ifpb.edu.br"
}

### Update host

PUT http://localhost:3000/hosts/3
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1NTczNzAzNiwiZXhwIjoxNjU1NzQwNjM2fQ.KdJzAj0kwBZ5phBchd9TITOGOGbd3KB4mniZLaasP3o

{
  "name": "Instituto Federal da Paraíba",
  "address": "www.ifpb.edu.br"
}

### Delete host

DELETE http://localhost:3000/hosts/5
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1NTczNzAzNiwiZXhwIjoxNjU1NzQwNjM2fQ.KdJzAj0kwBZ5phBchd9TITOGOGbd3KB4mniZLaasP3o

### Get time by host

GET http://localhost:3000/hosts/1/times
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1NTczNzAzNiwiZXhwIjoxNjU1NzQwNjM2fQ.KdJzAj0kwBZ5phBchd9TITOGOGbd3KB4mniZLaasP3o

### List all users

GET http://localhost:3000/users
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1NTczNzAzNiwiZXhwIjoxNjU1NzQwNjM2fQ.KdJzAj0kwBZ5phBchd9TITOGOGbd3KB4mniZLaasP3o

### Create user

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "teste",
  "email": "teste@email.com",
  "password": "123"
}

### Update user

PUT http://localhost:3000/users/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1NTczNzAzNiwiZXhwIjoxNjU1NzQwNjM2fQ.KdJzAj0kwBZ5phBchd9TITOGOGbd3KB4mniZLaasP3o

{
  "name": "test",
  "email": "test@email.com",
  "password": "12345678"
}

### Delete user

DELETE http://localhost:3000/users/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1NTczNzAzNiwiZXhwIjoxNjU1NzQwNjM2fQ.KdJzAj0kwBZ5phBchd9TITOGOGbd3KB4mniZLaasP3o"


### Signin

POST http://localhost:3000/signin
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "test"
}

### Signin

POST http://localhost:3000/signin
Content-Type: application/json

{
  "email": "teste@email.com",
  "password": "123"
}